import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import HeroUI from "@/components/shared/HeroUI";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/components/shared/ReduxProvider";
import AuthInitializer from "@/components/shared/AuthInitializer";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ThemeProvider } from "@/components/shared/ThemeProvider";

// Configure the Sans-Serif font (Body/UI)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Expose as a CSS variable
});

// Configure the Serif font (Headings)
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair", // Expose as a CSS variable
});

export const metadata = {
  title: "Publisha | Discover extraordinary ideas & stories",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${playfair.variable} antialiased`}
      >
        <ReduxProvider>
          <ThemeProvider>
            <HeroUI>
              <AuthInitializer>
                <Navbar />
                {children}
                <Footer />
              </AuthInitializer>
              <Toaster />
            </HeroUI>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
